---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
setwd("C:/Users/acvill/Dropbox/Phage/BacillusPaper-150Kb/J1_PhiNIT1/ani_aai_matrix/")

acc2name <- readr::read_tsv(file = "acc2name.txt",
                            col_names = c("seqname", "phage"))

read2mat <- function(data) {
  mat <- readr::read_tsv(file = data,
                         col_names = TRUE) |>
    mutate_if(is.double, ~ 100*(1 - .)) |>
    as.matrix()
  rownames(mat) <- mat[,1]
  mat <- mat[,-1]
  mat
}

aai_mat <- read2mat("W3_aai_matrix_14Aug2023.txt")
ani_mat <- read2mat("W3_ani_matrix_14Aug2023.txt")

ani_top    <- matrix(NA, nrow = nrow(aai_mat), ncol = ncol(aai_mat))
aai_bottom <- matrix(NA, nrow = nrow(aai_mat), ncol = ncol(aai_mat))

ani_top[upper.tri(ani_top)] <- ani_mat[upper.tri(ani_mat)]
aai_bottom[lower.tri(aai_bottom)] <- aai_mat[lower.tri(aai_mat)]

top_dat <- 
  as.data.frame(ani_top) |>
  `colnames<-`(colnames(ani_mat)) |>
  mutate(xvar = colnames(ani_mat)) |>
  pivot_longer(cols = -xvar, names_to = "yvar") |>
  mutate(value = as.double(value))

bottom_dat <- 
  as.data.frame(aai_bottom) |>
  `colnames<-`(colnames(aai_mat)) |>
  mutate(xvar = colnames(aai_mat)) |>
  pivot_longer(cols = -xvar, names_to = "yvar") |>
  mutate(value = as.double(value))
  
```

```{r}
tt <- ggplot(data = top_dat) +
  geom_tile(mapping = aes(x = xvar, y = yvar, fill = value),
            color = "black") +
  scale_fill_gradient(low = "white", high = "#f54242") +
  geom_text(mapping = aes(x = xvar, y = yvar, label = round(value, digits = 1))) +
  theme_bw() +
  coord_equal() +
  theme(axis.text = element_text(color = "black", size = 11),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title = element_blank(),
        legend.position = "none")

bb <- ggplot(data = bottom_dat) +
  geom_tile(mapping = aes(x = xvar, y = yvar, fill = value),
            color = "black") +
  scale_fill_gradient(low = "white", high = "#4287f5") +
  geom_text(mapping = aes(x = xvar, y = yvar, label = round(value, digits = 1))) +
  theme_bw() +
  coord_equal() +
  theme(axis.text = element_text(color = "black", size = 11),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title = element_blank(),
        legend.position = "none")

setwd("C:/Users/acvill/Dropbox/Phage/BacillusPaper-150Kb/J1_PhiNIT1/ani_aai_matrix/")

ggsave(filename = "ani_matrix_top_v3.pdf",
       plot = tt, device = cairo_pdf,
       width = 5.5,
       height = 5.5)

ggsave(filename = "aai_matrix_bottom_v3.pdf",
       plot = bb, device = cairo_pdf,
       width = 5.5,
       height = 5.5)
```

